### ISSUE TITLE
Remove wave name escaping in fit result code

### ISSUE THREAD

**Issue by legordian** [ROOTPWA-Maintainers/ROOTPWA#102]
Remove the wave name escaping snippets in the intensity and intensityErr functions in the fit result as this should not be done there, but in user space with the provided escaping function. Said escaping function has to be extended so that it includes escaping for "[", "]" and "\\\\".

**Comment by suhlatwork** [comment]
This should be fixed by #121. Can we close this issue?

**Comment by legordian** [comment]
We can and we should, thank you for pointing this out! Closed.
