### ISSUE TITLE
[Bug] TPWALikelihood::readDecayAmplitudes never sets firstWave to false [sf#23]

### ISSUE THREAD

**Issue by legordian** [ROOTPWA-Maintainers/ROOTPWA#23]
**Reported by sebastianuhl on 2013-10-14 15:08 UTC**
In the TPWALikelihood::readDecayAmplitudes method, the variable firstWave is never set to false. This means that the number of events in different amplitude files is not checked for consistency. Also the allocation of the temporary storage for the amplitudes from the current file would probably be a bit more efficient.

**Comment by suhlatwork** [comment]
Fixed in '_v2' by commit 2641ca68079d4966c405d88d44218875743753ba, to be ported to 'master'.

**Comment by suhlatwork** [comment]
Also fixed in the master with cb95b05fd70a3295a0cdf232b4163d257cb63c7e
