### ISSUE TITLE
exit 0 at the end of scripts

### ISSUE THREAD

**Issue by mmikhasenko** [ROOTPWA-Maintainers/ROOTPWA#232]
Bash scripts `compileBoostLibraries.sh` and `testMC.sh` (I guess others as well) are ended with `exit 0`
It causes that the terminal is shut independently on the script output. That is not how it is supposed to be, I guess.

To run and see output I used `echo $(. testMC.sh)` and `echo $(. compileBoostLibraries.sh)`
It is also not nice: there are no line brakes, and the output is printed only when the script is over.

Why do you do this?

**Comment by suhlatwork** [comment]
Those scripts are executable, you do not have to `source` them, but can directly run them (e.g. `./testMC.sh` if you are in the `test` directory, `PATH_TO/testMC.sh` to execute in any other directory).

**Comment by mmikhasenko** [comment]
My bad. I did not realize the difference.
Thanks. The issue is closed!
