### ISSUE TITLE
[Bug] fitresult::spinDensityMatrixElem() returns non-zero value for waves with different reflectivities [sf#25]

### ISSUE THREAD

**Issue by legordian** [ROOTPWA-Maintainers/ROOTPWA#25]
**Reported by bgrube on 2014-01-15 15:18 UTC**
Due to the block-diagonal form of the spin-density matrix in the reflectivity, the spin-density matrix element (interference term) for two waves with different reflectivity is zero. In the current implementation of fitresult::spinDensityMatrixElem() this is not checked and the function might return a non-zero value. This has consequences when fitResult::intensity(const char\* waveNamePattern) is called with a wave-name pattern that includes both positive and negative reflectivity (like e.g. "\*" for the total intensity). fitResult::intensity() also does not treat the flat wave as a special case.

At the moment the only solution is to parse the reflectivity value from the wave name.

**Comment by suhlatwork** [comment]
Supposedly fixed with cce54d667bec5b31a94fbfb92b4a9c83bfbbedbd
