### ISSUE TITLE
[Bug] evidence calculation is wrong for certain cases [sf#31]

### ISSUE THREAD

**Issue by legordian** [ROOTPWA-Maintainers/ROOTPWA#31]
**Reported by legordian on 2014-08-19 18:31 UTC**
As the determinant of the normalization matrix is wrong if there are thresholded waves, the evidence is wrongly calculated if there are waves with thresholds. The same is true for fits with both reflectivities (see also [bugs:#25]).

**Comment by suhlatwork** [comment]
Supposedly fixed by 5cd064443d002802db50e8e089a439d1ae227352.
