### ISSUE TITLE
operator<<(std::vector) does not handle empty vectors very well...

### ISSUE THREAD

**Issue by legordian** [ROOTPWA-Maintainers/ROOTPWA#80]
...meaning it leads to a segmentation violation.

**Comment by suhlatwork** [comment]
Already fixed in master by commit d92f65001f1d44d1092c13fa00e56c6d6b2b26ca (by you last August).

**Comment by legordian** [comment]
Aaahahahaha, nice one!

Did we backport this to _v2?

**Comment by suhlatwork** [comment]
Apparently not.

**Comment by legordian** [comment]
Ok then, new objective :D

We should backport d92f650 to _v2

**Comment by legordian** [comment]
Backport done in 3f1a9579, closed.
