### ISSUE TITLE
Try if -Wextra works

### ISSUE THREAD

**Issue by legordian** [ROOTPWA-Maintainers/ROOTPWA#81]
As suggested by Sebastian Uhl, we should try to add -Wextra and see if we can still compile.

**Comment by bgrube** [comment]
Well, we should give it a try, but when I did sometime ago it gave a LOT of warnings about stuff that did not seem to be really critical. It might only make sense when we bump up the minimum required compiler version as well.

**Comment by suhlatwork** [comment]
Enabled by default after merging #180 (commit b398322a9d336f682ac536b48df07c153431d14c).
